/** Messages Codex records with a user role even though they are generated by
 * the runtime and must not be presented as user-authored chat. */
export function isInternalUserMessageText(value: string): boolean {
  const text = value.trimStart();
  return text.startsWith("<environment_context>")
    || text.startsWith("<codex_internal_context_recovery>")
    || text.startsWith("<recommended_plugins>")
    || text.startsWith("<permissions instructions>")
    || text.startsWith("<app-context>")
    || /^# AGENTS\.md instructions(?:\r?\n|$)/.test(text)
    || /^<skill>\s*<name>[^<]+<\/name>\s*<path>[^<]+SKILL\.md<\/path>/.test(text);
}
